services:
  bk:
    container_name: bot_web_bk
    build:
      context: ./character_bot_personalization_web/character_bot_bk
      dockerfile: Dockerfile
    
    ports:
      - "8000:8000"

  config:
    container_name: bot_web_config
    build:
      context: ./telegram_bot_configuration
      dockerfile: Dockerfile
